### PR TITLE
Implement async#job#wait()

### PR DESCRIPTION
**Pull request by k-takata**
Implement it following the spec of https://neovim.io/doc/user/eval.html#jobwait().

### CODE REVIEW

**Comment by prabirshrestha** [comment]
I haven't played around with `jobwait` but curious what the scenario is that you are trying to enable?

**Comment by k-takata** [comment]
I use it in k-takata/minpac#34.
It might not be a usual use case, but  I wanted to implement a replacement for `system()`.
The difference of the function from `system()` is that it doesn't open a new console window on Windows.
Actually, I can implement it without `jobwait`, but using it is straight forward.

**Comment by prabirshrestha** [comment]
- Does this block vim/neovim or would it still be responsive?
- Can you add an example in README.md

**Comment by k-takata** [comment]
> Does this block vim/neovim or would it still be responsive?

It blocks vim/neovim, but users can interrupt it by hitting Ctrl+C.
Callbacks for jobs/channels can be still executed.

**Comment by prabirshrestha** [comment]
Will have a look at this by end of this week.

**Comment by prabirshrestha** [comment]
Merged. Thanks for updating the docs too.

**Comment by k-takata** [comment]
Maybe you can close #6.

**Comment by prabirshrestha** [comment]
Done

**Pull request merged**
