### PR TITLE
refactor take 2

### PR DESCRIPTION
**Pull request by prabirshrestha**
refactor so it is easy to change the default job type and easier to add in the future.
also fixes `async#job#send` in vim

### CODE REVIEW

**Comment by wsdjeg** [comment]
nice work, but can use test https://github.com/vim/vim/issues/1198, I am not sure vim8's job support backgroud terminal app.

**Comment by wsdjeg** [comment]
nice work, but can you test https://github.com/vim/vim/issues/1198, I am not sure vim8's job support backgroud terminal app.

**Comment by wsdjeg** [comment]
nice work, but can you test https://github.com/vim/vim/issues/1198, I am not sure vim8's job support backgroud terminal app.

**Comment by wsdjeg** [comment]
nice work, but can you test https://github.com/vim/vim/issues/1198, I am not sure vim8's job support backgroud terminal app.

**Comment by wsdjeg** [comment]
nice work, but can you test https://github.com/vim/vim/issues/1198, I am not sure vim8's job support backgroud terminal app.

**Comment by wsdjeg** [comment]
nice work, but can you test https://github.com/vim/vim/issues/1198, I am not sure vim8's job support backgroud terminal app.

**Comment by wsdjeg** [comment]
nice work, but can you test https://github.com/vim/vim/issues/1198, I am not sure vim8's job support backgroud terminal app.

**Comment by wsdjeg** [comment]
nice work, but can you test https://github.com/vim/vim/issues/1198, I am not sure vim8's job support backgroud terminal app.

**Comment by wsdjeg** [comment]
nice work, but can you test https://github.com/vim/vim/issues/1198, I am not sure vim8's job support backgroud terminal app.

**Comment by wsdjeg** [comment]
nice work, but can you test https://github.com/vim/vim/issues/1198, I am not sure vim8's job support backgroud terminal app.

**Comment by prabirshrestha** [comment]
Found some bugs and pushed the changes.

``` sh
go get github.com/sourcegraph/go-langserver/langserver/cmd/langserver-go
```

Here is the screenshot showing that it works on both vim and neovim. Notice the stdin, stdout and stderr in the screenshot.

This is for https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md

image

Here is the script in case you are curious.

``` vim
function! s:_logjobargs(jobid, data, event)
    echom a:event . '('. a:jobid .'):' . join(a:data, "\r\n")
endfunction

function! s:_on_stdout(jobid, data, event)
    call s:_logjobargs(a:jobid, a:data, a:event)
endfunction

function! s:_on_stderr(jobid, data, event)
    call s:_logjobargs(a:jobid, a:data, a:event)
endfunction

function! s:_on_stdexit(jobid, status, event)
    call s:_logjobargs(a:jobid, a:status, a:event)
endfunction

let g:_job = async#job#start(['langserver-go'], {
    \ 'on_stdout': function('s:_on_stdout'),
    \ 'on_stderr': function('s:_on_stderr'),
    \ 'on_stdexit': function('s:_on_stdexit'),
\})

if g:_job > 0
    let s:seq = 0
    function! s:_send(opts) " opts: { method, params? }
        let s:seq  = s:seq + 1
        let l:msg = { 'jsonrpc': '2.0', 'id': s:seq, 'method': a:opts.method }
        if has_key(a:opts, 'params')
            let l:msg.params = a:opts.params
        endif
        let l:json = json_encode(l:msg)
        let l:req_data = 'Content-Length: ' . len(l:json) . "\r\n\r\n" . l:json
        echom 'stdin('.s:seq.')' l:req_data
        call async#job#send(g:_job, l:req_data)
    endfunction

    call s:_send({ 'method': 'initialize' })
else
    echom 'failed to start job ' . g:_job
endif
```

**Comment by wsdjeg** [comment]
@prabirshrestha does the plugin support run `irssi` via vim8's job? I just test it, but it dees not work.

**Comment by prabirshrestha** [comment]
@wsdjeg based on the comment in the vim issue seems like `irssi` doesn't support stdin/stdout. If that is the case you would need to create another executable wrapper so that vim talks with stdin/stdout with the wrapper which then delegates proper call to irssi based on what ever protocol it supports.

**Comment by wsdjeg** [comment]
but how does irssi works well with neovim's job api? neovim's job api do not use stdin/stdout?

**Comment by wsdjeg** [comment]
but how does irssi works well with neovim's job api? neovim's job api do not use stdin/stdout?

**Comment by prabirshrestha** [comment]
i have no idea about that. Might be start an issue on vim mailing list instead?

**Comment by wsdjeg** [comment]
I have created issue in vim repo, I do not use the google maillist.

**Pull request merged**
